# -*- coding: utf-8 -*-
"""Tech layoffs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xxThKCMdTlu14-yn3mhFSnENKFS8--bY
"""

# prompt: df = read cs '/content/sample_data/tech_layoffs.xlsx' df.head()

import pandas as pd
data = pd.read_excel('/content/sample_data/tech_layoffs.xlsx')
data.head()

data.info()

data.describe(
)

import matplotlib.pyplot as plt

# Calcular la distribución de despidos por industria
industry_layoffs = data.groupby('Industry')['Laid_Off'].sum().sort_values(ascending=False)

# Visualizar la distribución
plt.figure(figsize=(8, 5))
industry_layoffs.plot(kind='bar', color='skyblue')
plt.title('Distribución de Despidos por Industria')
plt.xlabel('Industria')
plt.ylabel('Número de Despidos')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

plt.show()



map_file_path = '/content/sample_data/mapa.html'



import folium
from folium.plugins import MarkerCluster

# Crear un mapa centrado en una ubicación global
mapa_despidos = folium.Map(location=[20, 0], zoom_start=2)

# Agrupar los marcadores para mejorar la visualización
marker_cluster = MarkerCluster().add_to(mapa_despidos)

# Añadir los despidos al mapa
for idx, row in data.iterrows():
    folium.Marker(
        location=[row['lat'], row['lng']],
        popup=f"{row['Company']}: {row['Laid_Off']} despidos",
        icon=folium.Icon(color='red', icon='info-sign')
    ).add_to(marker_cluster)

# Guardar el mapa en un archivo HTML
mapa_despidos.save(map_file_path)

map_file_path

# Para analizar la tendencia de despidos a lo largo del tiempo, vamos a agrupar los datos por fecha de despidos
# y sumar el número total de despidos por cada fecha.

# Convertir la fecha de despidos a mes y año para agrupación
data['Month_Year'] = data['Date_layoffs'].dt.to_period('M')

# Agrupar por la nueva columna 'Month_Year' y sumar los despidos
trend_data = data.groupby('Month_Year')['Laid_Off'].sum().reset_index()
trend_data['Month_Year'] = trend_data['Month_Year'].astype(str)  # Convertir a string para visualización

# Visualizar la tendencia de despidos a lo largo del tiempo
plt.figure(figsize=(12, 5))
plt.plot(trend_data['Month_Year'], trend_data['Laid_Off'], marker='o', linestyle='-', color='blue')
plt.title('Tendencia de Despidos a lo Largo del Tiempo')
plt.xlabel('Fecha (Mes y Año)')
plt.ylabel('Número de Despidos')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()

plt.show()

# Para analizar los despidos según la etapa de la empresa, agruparemos los datos por la columna 'Stage'
# y sumaremos el número total de despidos para cada etapa.

stage_layoffs = data.groupby('Stage')['Laid_Off'].sum().sort_values(ascending=False)

# Visualizar la distribución de despidos por etapa de la empresa
plt.figure(figsize=(8, 6))
stage_layoffs.plot(kind='bar', color='purple')
plt.title('Distribución de Despidos por Etapa de la Empresa')
plt.xlabel('Etapa de la Empresa')
plt.ylabel('Número de Despidos')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

plt.show()

